#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
BASE=b982d4d0c8686e5c5fcb965633d34a4e0ba46fcf
CANDIDATE=186df3daa27d7b3541da694190d6f8ec9fab7da6

changed_src="$(git diff --name-only "$BASE" -- src)"
[[ -z "$changed_src" ]] || {
  echo 'FVQ45_UNEXPECTED_PRODUCTION_DELTA' >&2
  printf '%s\n' "$changed_src" >&2
  exit 1
}
echo 'FVQ45_NO_PRODUCTION_DELTA=PASS'

changed_ref="$(git diff --name-only "$BASE" -- reference)"
[[ -z "$changed_ref" ]] || {
  echo 'FVQ45_UNEXPECTED_REFERENCE_DELTA' >&2
  printf '%s\n' "$changed_ref" >&2
  exit 1
}
echo 'FVQ45_NO_REFERENCE_DELTA=PASS'

if grep -Eiq 'tests/fpm/.*fpm08b|F-PM08B_DISTRIBUTION_EVIDENCE|run_fpm08b' tests/fvq/test_fvq45_divdra_spatial_distribution.py; then
  echo 'FVQ45_INDEPENDENT_ORACLE_STATIC_SEPARATION=FAIL' >&2
  exit 1
fi
echo 'FVQ45_INDEPENDENT_ORACLE_STATIC_SEPARATION=PASS'

actual_blob="$(git rev-parse "$CANDIDATE:src/process/mod_drainage_spatial_distribution.f90")"
[[ "$actual_blob" == '9e4a196eecf971698b16d4a882f5aa8b32b66ebe' ]]
echo 'FVQ45_CANDIDATE_BLOB_PRECHECK=PASS'

python3 tests/fvq/test_fvq45_divdra_spatial_distribution.py | tee /tmp/fvq45-output.txt

for marker in \
  'FVQ45_FROZEN_DIVDRA_SOURCE_IDENTITY=PASS' \
  'FVQ45_EQUATION_LEVEL_EXCERPT_BINDING=PASS' \
  'FVQ45_CANDIDATE_CLOSEOUT_BLOB_IDENTITY=PASS' \
  'FVQ45_MASS_AND_SCRATCH_OWNERSHIP_STATIC_BINDING=PASS' \
  'FVQ45_O0_O2_PARSED_RESULT_IDENTITY=PASS' \
  'FVQ45_STABLE_DOMAIN_RANDOMIZED_COVERAGE=PASS' \
  'FVQ45_TRUNCATED_AND_FULL_PROFILE_COVERAGE=PASS' \
  'FVQ45_SINGLE_COMPARTMENT_SPECIAL_CASE_COVERAGE=PASS' \
  'FVQ45_STABLE_DOMAIN_NODE_DISTRIBUTION_EQUIVALENCE=PASS' \
  'FVQ45_STABLE_DOMAIN_HYDRAULIC_GEOMETRY_EQUIVALENCE=PASS' \
  'FVQ45_LAST_NODE_ROUNDOFF_CLOSURE_ONLY=PASS' \
  'FVQ45_LEV2COMP_BOUNDARY_SEAM_COVERAGE=PASS' \
  'FVQ45_LEV2COMP_BOUNDARY_SEAM_MISMATCH_CONFIRMED=PASS' \
  'FVQ45_ZERO_TRANSFER_DEPENDENCY_FREE_ROUTE=PASS' \
  'FVQ45_HELD_POSITIVE_SMALL_INTERVAL_FAILS_CLOSED=PASS' \
  'FVQ45_STABLE_DOMAIN_SCIENTIFIC_EQUIVALENCE=PASS' \
  'FVQ45_FULL_FPM08B_SCIENTIFIC_QUALIFICATION=NO' \
  'FVQ45_DECISION=NOT_QUALIFIED_FPM08B_LEV2COMP_BOUNDARY_SEAM_REMEDIATION_REQUIRED'; do
  grep -Fq "$marker" /tmp/fvq45-output.txt
 done

echo 'FVQ45_DIVDRA_SPATIAL_DISTRIBUTION_DISPOSITION_GATE=PASS'
