import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "research" / "hydrofit"))
from hydrofit import FitConfig, MvGParameters, Observation, evaluate, fit, multistart_fit, near_equivalent_ensemble, swap_theta, textbook_theta


def synthetic_observations(p, semantics="swap_default_mvg"):
    heads = np.array([-0.005, -0.01, -0.1, -1.0, -10.0, -100.0, -1000.0, -10000.0])
    theta, kval = evaluate(heads, p, semantics)
    obs = [Observation("theta", float(h), float(v), sigma=1e-3) for h, v in zip(heads, theta)]
    obs += [Observation("K", float(h), float(v), sigma=0.02) for h, v in zip(heads, kval)]
    return obs


def test_forward_physical_limits():
    p = MvGParameters(0.05, 0.45, 0.02, 1.6, 50.0)
    heads = np.array([0.0, -1e-3, -1.0, -100.0, -1e6])
    theta, kval = evaluate(heads, p, "swap_default_mvg")
    assert np.all(theta >= p.theta_r)
    assert np.all(theta <= p.theta_s)
    assert np.all(kval > 0.0)
    assert np.all(kval <= p.Ks)


def test_near_saturation_semantics_are_not_silently_equivalent():
    p = MvGParameters(0.05, 0.45, 0.5, 1.6, 50.0, h_entry=0.0)
    h = np.array([-0.005])
    assert abs(float(swap_theta(h, p)[0] - textbook_theta(h, p)[0])) > 1e-8


def test_exact_synthetic_recovery_swap_native():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0)
    initial = MvGParameters(0.10, 0.48, 0.008, 1.4, 15.0)
    result = fit(synthetic_observations(truth), initial, cfg)
    assert result.success
    got = result.parameters
    assert np.allclose(
        [got.theta_r, got.theta_s, got.alpha, got.n, got.Ks],
        [truth.theta_r, truth.theta_s, truth.alpha, truth.n, truth.Ks],
        rtol=2e-5, atol=2e-7,
    )
    assert result.objective < 1e-8


def test_information_removal_worsens_identifiability():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0)
    initial = MvGParameters(0.10, 0.48, 0.008, 1.4, 15.0)
    full = synthetic_observations(truth)
    reduced = [o for o in full if o.family == "theta" and -100.0 <= o.head_cm <= -0.1]
    a = fit(full, initial, cfg)
    b = fit(reduced, initial, cfg)
    assert np.isfinite(a.condition_number)
    assert b.condition_number > a.condition_number or not np.isfinite(b.condition_number)


def test_multistart_converges_to_same_exact_solution():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0)
    starts = [
        MvGParameters(0.02, 0.36, 0.003, 1.2, 5.0),
        MvGParameters(0.12, 0.55, 0.08, 2.5, 150.0),
        MvGParameters(0.08, 0.46, 0.012, 1.5, 25.0),
    ]
    best, results = multistart_fit(synthetic_observations(truth), starts, cfg)
    assert best.success
    assert len(results) == 3
    for result in results:
        assert result.success
        p = result.parameters
        assert np.allclose(
            [p.theta_r, p.theta_s, p.alpha, p.n, p.Ks],
            [truth.theta_r, truth.theta_s, truth.alpha, truth.n, truth.Ks],
            rtol=5e-5, atol=5e-7,
        )


def test_theta_only_exposes_unidentifiable_ks_direction():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0)
    all_obs = synthetic_observations(truth)
    theta_only = [o for o in all_obs if o.family == "theta"]
    initial = MvGParameters(0.10, 0.48, 0.008, 1.4, 15.0)
    result = fit(theta_only, initial, cfg)
    assert result.success
    assert result.singular_values[-1] < 1e-10 or not np.isfinite(result.condition_number) or result.condition_number > 1e12


def test_current_sum_weighting_is_replication_sensitive():
    # Deliberately inconsistent families: theta is generated by one soil, K by another.
    theta_truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    k_truth = MvGParameters(0.06, 0.43, 0.022, 1.55, 55.0)
    heads = np.array([-0.1, -1.0, -10.0, -100.0, -1000.0])
    theta, _ = evaluate(heads, theta_truth, "swap_default_mvg")
    _, kval = evaluate(heads, k_truth, "swap_default_mvg")
    obs = [Observation("theta", float(h), float(v), sigma=0.01) for h, v in zip(heads, theta)]
    obs += [Observation("K", float(h), float(v), sigma=0.1) for h, v in zip(heads, kval)]
    replicated = [o for o in obs if o.family == "K"] + [o for o in obs if o.family == "theta"] * 20
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0)
    initial = MvGParameters(0.08, 0.46, 0.012, 1.5, 30.0)
    a = fit(obs, initial, cfg)
    b = fit(replicated, initial, cfg)
    va = np.array([a.parameters.theta_r, a.parameters.theta_s, a.parameters.alpha, a.parameters.n, a.parameters.Ks])
    vb = np.array([b.parameters.theta_r, b.parameters.theta_s, b.parameters.alpha, b.parameters.n, b.parameters.Ks])
    assert np.max(np.abs((vb - va) / np.maximum(np.abs(va), 1e-12))) > 1e-3


def _inconsistent_joint_case():
    theta_truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    k_truth = MvGParameters(0.06, 0.43, 0.022, 1.55, 55.0)
    heads = np.array([-0.1, -1.0, -10.0, -100.0, -1000.0])
    theta, _ = evaluate(heads, theta_truth, "swap_default_mvg")
    _, kval = evaluate(heads, k_truth, "swap_default_mvg")
    obs = [Observation("theta", float(h), float(v), sigma=0.01) for h, v in zip(heads, theta)]
    obs += [Observation("K", float(h), float(v), sigma=0.1) for h, v in zip(heads, kval)]
    return obs


def test_family_mean_is_invariant_to_exact_theta_replication():
    obs = _inconsistent_joint_case()
    replicated = [o for o in obs if o.family == "K"] + [o for o in obs if o.family == "theta"] * 20
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0, weighting_mode="family_mean")
    initial = MvGParameters(0.08, 0.46, 0.012, 1.5, 30.0)
    a = fit(obs, initial, cfg)
    b = fit(replicated, initial, cfg)
    va = np.array([a.parameters.theta_r, a.parameters.theta_s, a.parameters.alpha, a.parameters.n, a.parameters.Ks])
    vb = np.array([b.parameters.theta_r, b.parameters.theta_s, b.parameters.alpha, b.parameters.n, b.parameters.Ks])
    assert np.allclose(va, vb, rtol=2e-5, atol=2e-7)


def test_family_mean_preserves_exact_synthetic_recovery():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0, weighting_mode="family_mean")
    initial = MvGParameters(0.10, 0.48, 0.008, 1.4, 15.0)
    result = fit(synthetic_observations(truth), initial, cfg)
    got = result.parameters
    assert result.success
    assert np.allclose(
        [got.theta_r, got.theta_s, got.alpha, got.n, got.Ks],
        [truth.theta_r, truth.theta_s, truth.alpha, truth.n, truth.Ks],
        rtol=2e-5, atol=2e-7,
    )


def _limited_perturbed_case():
    truth = MvGParameters(0.06, 0.43, 0.015, 1.7, 35.0)
    theta_heads = np.array([-1.0, -10.0, -100.0, -1000.0])
    k_heads = np.array([-10.0, -1000.0])
    theta, _ = evaluate(theta_heads, truth, "swap_default_mvg")
    _, kval = evaluate(k_heads, truth, "swap_default_mvg")
    theta_delta = np.array([0.0015, -0.0020, 0.0010, -0.0015])
    logk_delta = np.array([0.04, -0.05])
    obs = [Observation("theta", float(h), float(v + d), sigma=0.01) for h, v, d in zip(theta_heads, theta, theta_delta)]
    obs += [Observation("K", float(h), float(v * np.exp(d)), sigma=0.1) for h, v, d in zip(k_heads, kval, logk_delta)]
    return truth, obs


def test_near_equivalent_ensemble_is_nested_and_nontrivial():
    truth, obs = _limited_perturbed_case()
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0, weighting_mode="family_mean")
    starts = [
        MvGParameters(0.03, 0.38, 0.005, 1.25, 8.0),
        MvGParameters(0.12, 0.52, 0.05, 2.3, 120.0),
        MvGParameters(0.08, 0.46, 0.012, 1.5, 25.0),
    ]
    ens = near_equivalent_ensemble(obs, starts, cfg, local_draws=1500, broad_draws=1500)
    assert np.all(~ens.tight_mask | ens.primary_mask)
    assert np.all(~ens.primary_mask | ens.wide_mask)
    assert ens.primary_mask.sum() > 1
    kept = ens.candidates[ens.primary_mask]
    spread = np.ptp(kept, axis=0)
    assert np.any(spread > np.array([1e-4, 1e-4, 1e-5, 1e-3, 1e-2]))
    for x, j in zip(ens.candidates[ens.primary_mask], ens.objectives[ens.primary_mask]):
        assert np.isfinite(j)
        assert j <= ens.optimum.objective + max(0.05 * ens.optimum.objective, 0.25) + 1e-12


def test_ensemble_seed_is_deterministic():
    _, obs = _limited_perturbed_case()
    cfg = FitConfig(semantics="swap_default_mvg", fixed_l=0.5, fixed_h_entry=0.0, weighting_mode="family_mean")
    starts = [MvGParameters(0.08, 0.46, 0.012, 1.5, 25.0)]
    a = near_equivalent_ensemble(obs, starts, cfg, seed=123, local_draws=300, broad_draws=300)
    b = near_equivalent_ensemble(obs, starts, cfg, seed=123, local_draws=300, broad_draws=300)
    assert np.array_equal(a.candidates, b.candidates)
    assert np.array_equal(a.objectives, b.objectives)
    assert np.array_equal(a.primary_mask, b.primary_mask)
